### ISSUE TITLE
Intercontainer communication 

### ISSUE THREAD

**Issue by ramateur** [lowescott/learning-tools#1]
Is it possible to communicate between containers on separate nodes? Can mpi applications be executed on such virtual cluster?

**Comment by lowescott** [comment]
You'd need some sort of networking solution to connect the containers on the separate nodes. There are a few new solutions out there for this: Flannel, Weave, etc. Docker itself is re-working networking (following the SocketPlane acquisition), so you can expect to see some changes there. The Open vSwitch team is also launching an effort called Open Virtual Network (OVN) that will provide container-to-container connectivity. Does that help?

**Comment by ramateur** [comment]
Thanks. It helps to understand that some networking solution is needed. Right now I run Docker containers on compute nodes with --net=host option, but it considered unsecure.

**Comment by lowescott** [comment]
Happy to help! Closing this issue.
