### ISSUE TITLE
Linking to other peoples stuff?

### ISSUE THREAD

**Issue by JKhawaja** [lowescott/learning-tools#11]
Hey Scott,

This seems like a really cool idea! :smile: What do you think about linking to other peoples "tutorials" for distributed systems tools? 

e.g. 

- https://github.com/kelseyhightower/kubernetes-fleet-tutorial
- https://github.com/bketelsen/coreos-kubernetes-digitalocean

**Comment by lowescott** [comment]
@JKhawaja I certainly don't have a problem adding links to the README.md to point people to other useful projects, but I don't have time to maintain such a curated list of useful links. I would be open, however, to merging a PR that added such links, if you're interested in contributing. I'd suggest adding a new section to the README.md file to hold links to other useful projects.

**Comment by JKhawaja** [comment]
That sounds simple enough. I'll try to remember to do that soon! Thanks! :)

**Comment by lowescott** [comment]
@JKhawaja If you need/want any help in actually creating and submitting the PR, let me know. Happy to help walk you through the process. (If you're familiar with the process, then just ignore this.) :-)

I'll leave this issue open until such time as you (or someone else) gets around to creating the PR, at which point you can reference this issue number in the commit message for reference.

**Comment by JKhawaja** [comment]
@lowescott would you like me to just name the section in the readme 'Other Useful Projects'?

**Comment by JKhawaja** [comment]
@lowescott  please let me know if there is something about the PR that you want me to change.

**Comment by lowescott** [comment]
@JKhawaja Just merged your PR. Thanks! Closing this issue now.
