### ISSUE TITLE
Can not run on VirtualBox 

### ISSUE THREAD

**Issue by kerrer** [lowescott/learning-tools#47]
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: slowe/ubuntu-trusty-x64
Address: https://atlas.hashicorp.com/slowe/ubuntu-trusty-x64
Requested provider: [:virtualbox]

**Comment by lowescott** [comment]
@kerrer The Vagrant boxes that I provide (such as the slowe/ubuntu-trusty-x64 box referenced above) are only formatted for VMware products (VMware Fusion and/or VMware Workstation). For a Vagrant box formatted for VirtualBox, I'd recommend using ubuntu/trusty64.

I'll go ahead and close this issue for now, but if you have further questions/comments don't hesitate to re-open it. Thanks!
