### ISSUE TITLE
Running a Consul Cluster in Vagrant

### ISSUE THREAD

**Issue by LucianYoga** [lowescott/learning-tools#51]
I don’t see boostrap.json file. Will you be able to commit that file?

**Comment by lowescott** [comment]
@LucianYoga Sorry, that's a typo. The `bootstrap.json` file doesn't exist and shouldn't be necessary. Instead, the `server.json` file takes its place. I'll update the README so that references to `bootstrap.json` are removed. Is the environment working for you otherwise?

**Comment by LucianYoga** [comment]
Thanks and appreciate your response.  I figured after reading further it may be a type but wanted to make sure. Yes it works great! Thanks again.  I do have a follow up question if you don't mind. Will this work with Vagrant and VirtualBox combo?

**Comment by lowescott** [comment]
@LucianYoga Yes, it should work with both VirtualBox as well as VMware Fusion/Workstation. Note that you'll need an appropriate box installed for the corresponding provider, and you'll need to note the name of the box in `machines.yml`. The VMware box name should be listed on the lines for "vmw_box", and the VirtualBox box name should be listed on the "vb_box" lines.

**Comment by lowescott** [comment]
@LucianYoga I just finished testing this environment w/ VirtualBox. There are some issues with the Consul configuration. I'll be committing some changes shortly that should address those issues, so be sure to pull down the latest version of the files before you use it with VirtualBox.

**Comment by LucianYoga** [comment]
Awesome! Thanks for your help.  I'll pull down your latest changes and give it shot whenever you have it ready.

**Comment by lowescott** [comment]
@LucianYoga I've committed the changes to make this work as expected on both VMware Fusion (and possibly Workstation, though I haven't tested that) and VirtualBox. I've also updated the README, which was horribly out of date (I apologize for that). If you run into any problems using the environment, let me know.

By the way, you should be able to easily update this environment to use a more recent Consul binary by editing `consul.sh`, if you like.
