### ISSUE TITLE
Add aws.instance_type=instances['instance_type'] to vagrant-aws/Vagrantfile

### ISSUE THREAD

**Issue by frjaraur** [lowescott/learning-tools#54]
Add aws.instance_type=instances['instance_type'] to vagrant-aws/Vagrantfile because if not it will always use default values... (m3.medium) which is not the cheapest node to test ;)

Thnks,
Javier R.

**Comment by lowescott** [comment]
Closing this issue, fixed via 5a061b1. Thanks!

**Comment by frjaraur** [comment]
Thanks for developing all these tools!!
Javier R.
