### ISSUE TITLE
Error on vagrant up

### ISSUE THREAD

**Issue by d3haynes** [lowescott/learning-tools#55]
Hi,

going through your instructions, I receive this error.

A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: "docker" "ps" "-a" "-q" "--no-trunc"

Stderr: Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Stdout:

If I then run vagrant up again, I receive this...

A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: "docker" "run" "--name" "nginx-container" "-d" "-p" "80:80" "-p" "443:443" "nginx"

Stderr: Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
6a5a5368e0c2: Pulling fs layer
4aceccff346f: Pulling fs layer
c8967f302193: Pulling fs layer
c8967f302193: Verifying Checksum
c8967f302193: Download complete
4aceccff346f: Verifying Checksum
4aceccff346f: Download complete
6a5a5368e0c2: Verifying Checksum
6a5a5368e0c2: Download complete
6a5a5368e0c2: Pull complete
4aceccff346f: Pull complete
c8967f302193: Pull complete
Digest: sha256:1ebfe348d131e9657872de9881fe736612b2e8e1630e0508c354acb0350a4566
Status: Downloaded newer image for nginx:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint nginx-container (8ade69b7e43443ebe5fdb52368b6cf3f9017dfb46c992cd6ed257bea095ec705): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.

Stdout: 78d3ec7da7a4031c212ea7a0fbbfed4214dadffacc0f7f6ca0842b7861bd7c42

Any insight would be helpful. I have been using Vagrant for over a year with a custom vagrant file for multiple vhosts, but am just now playing around with Docker. I am on a windows machine...I know I know haha.

Thanks!

**Comment by lowescott** [comment]
@d3haynes In what environment is this occurring?

**Comment by d3haynes** [comment]
@lowescott I think I finally got somewhere, I changed docker.ports to 8080:80 instead of 80:80 and the error went away. I was actually able to get the nginx welcome page, trying to get a wordpress image with mysql on there now and run through all of that, very new to docker.....does changing the host:guest port like that sound ok to you? thanks for your help!

**Comment by lowescott** [comment]
@d3haynes Yes, in looking back at your original message the error comes from trying to bind the container to port 80 when port 80 is already in use (see the very end of the error message you originally posted). So, changing the port mapping would fix the problem and allow the container to start. I'll go ahead and close this issue for now, but feel free to re-open it if necessary.
