### ISSUE TITLE
vagrant-docker

### ISSUE THREAD

**Issue by pheer** [lowescott/learning-tools#6]
On mac osx.

Command: "docker" "ps" "-a" "-q" "--no-trunc"

Stderr: Get http:///var/run/docker.sock/v1.19/containers/json?all=1: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?

Any ideas?

**Comment by lowescott** [comment]
Are you trying to run the `docker` command directly from your OS X system? That won't work; this particular Vagrant environment doesn't configure the Docker daemon to listen remotely, and you'd also need to set your DOCKER_HOST variable on OS X. You should, however, be able to run various `docker` commands from within the VM created by this Vagrant environment.

**Comment by pheer** [comment]
No not directly.  I'm using the "host" file configuration where the host is a vagrant vm.  All I'm doing is a vagrant up.

**Comment by lowescott** [comment]
@pheer If you're SSH'd into the VM (defined in `host/Vagrantfile`), then you should be able to run whatever `docker` commands you need; the Docker daemon is installed into that VM as part of the Vagrant setup. So, you just need to do a `vagrant up`, followed by `vagrant ssh docker-host` to connect to the Linux VM where the Docker daemon is running. Let me know if that helps.

**Comment by pheer** [comment]
I mean I can't even do a 'vagrant up' on that project without that error I pasted.

**Comment by lowescott** [comment]
@pheer Ah, yes, I see the problem. It looks like there may be an issue with the Docker provisioner in Vagrant, which is responsible for installing Docker into the host VM (I just replicated the error on my system). Let me try some troubleshooting to see if there's anything I can do.

**Comment by pheer** [comment]
Cool.  I'll dig around as well.  Let me know if I can help

**Comment by lowescott** [comment]
@pheer Can you confirm the details on your system setup? (Virtualization platform, OS version, Vagrant version, etc.) Thanks!

**Comment by pheer** [comment]
Virtualbox: 4.3.32
Mac: 10.9.5
vagrant: 1.7.4
docker machine: 0.4.1

**Comment by lowescott** [comment]
@pheer This issue is related to a known problem with the Vagrant Docker provisioner (see https://github.com/mitchellh/vagrant/issues/3998). I've added the code listed in that comment thread to `host/Vagrantfile` and it appears (based on my testing) to fix the problem (see #7). Please test and let me know. Thanks!

**Comment by lowescott** [comment]
@pheer Also, this Vagrant plugin may also resolve the error (but note that I have not tested this yet): https://github.com/aidanns/vagrant-reload

**Comment by shankarramshivram** [comment]
@lowescott  - I am seeing the same problem. 
I tried again after added the inline shell command for ssh kill. It still doesn't  work :( ..
it works only when  i change the config username in the host-docker Vagrant file to root

**Comment by lowescott** [comment]
@shankarramshivram Sounds like perhaps a sudo permissions error? What Vagrant box are you using?

**Comment by lowescott** [comment]
@shankarramshivram Is this problem still occurring, or can I close this issue?

**Comment by lowescott** [comment]
Closing this issue. If anyone else sees this same problem, feel free to re-open.
