### ISSUE TITLE
Feature: Add Packer?

### ISSUE THREAD

**Issue by inetbiz** [lowescott/learning-tools#77]
Would you mind adding packer to your folders?

**Comment by lowescott** [comment]
@inetbiz Is there a particular use case for Packer? Also, I would welcome contributions to add Packer examples and use cases, if you'd be interested in contributing them.

**Comment by inetbiz** [comment]
@lowescott still learning. I'll definitely help participate once I'm proficient enough.

**Comment by lowescott** [comment]
@inetbiz I'll see what I can do. It's not a technology with which I'm actively working, though I do have a couple use cases where I might be handy. I'll leave this issue open until such time as I can actually contribute some Packer-related content.

**Comment by inetbiz** [comment]
@lowescott it is my understanding that you could build the vm using packer and just have the bare minimum in the box build? Adding packages after the person has created the vagrant box. Is that so?

**Comment by lowescott** [comment]
@inetbiz Yes. You could use Packer to create a bare-bones Vagrant box (or AMI---multiple outputs are available), then use that box in a Vagrant workflow which installs additional packages as needed.

**Comment by lowescott** [comment]
Closing this issue due to lack of further communication.
